version: '3.7'

services:
  mailhog:
    container_name: boon-infra-mailhog
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_UI_PORT}:8025
    restart: unless-stopped
  seq:
    container_name: boon-seq
    image: datalust/seq:latest
    ports:
      - ${SEQ_UI_PORT}:80
      - ${SEQ_SERVER_PORT}:5341
    volumes:
      - ./logs/seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QCxh/LN52rQ/pGlajPfJpqdopsx7IX9KAi+5rcU2hETBxfjjHQXydaN9kO9h2n/yKB1DbxnmGULOSlfgsTZRbjUF/wQBrBpbELhUTybNwhAw
      - BASE_URI=${SEQ_UI_HOST}:${SEQ_UI_PORT}
    restart: always
