---
- hosts: dev
  vars:
    - docker_compose_version: 'v2.27.0'
    - app_user_username: 'user_git'
  tasks:
    - name: Install docker prerequisites
      become: true
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - vim
        - haveged
        - python3-pip

    - name: Add docker GPG apt key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker PPA
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install docker module for python
      become: true
      pip:
        name: docker

    - name: Install docker compose
      become: true
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 755  

    - name: Create docker group (for root-less docker)
      become: true
      group:
        name: docker
        state: present

    - name: Add user to the docker group (for root-less docker)
      become: true
      user:
        name: "{{ app_user_username }}"
        groups: docker
        append: true

    - name: Install docker-compose module for python
      become: true
      pip:
        name: docker-compose        